START TRANSACTION; 

CREATE TABLE IF NOT EXISTS songs (
  id VARCHAR(40) NOT NULL,
  studio_id VARCHAR(40) NOT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  name VARCHAR(50) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS versions (
  id VARCHAR(40) NOT NULL,
  song_id VARCHAR(40) NOT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  name VARCHAR(50) NOT NULL,
  PRIMARY KEY (id)
);

COMMIT;
