START TRANSACTION;

ALTER TABLE invitations 
ADD COLUMN id VARCHAR(40) NOT NULL,
ADD COLUMN created_at DATETIME NOT NULL,
ADD COLUMN updated_at DATETIME NOT NULL;

ALTER TABLE invitations 
ADD UNIQUE (id);

COMMIT;